name: One-Time Merge PR

on:
  schedule:
    # Runs at 2025-09-01 18:29 UTC = 2025-09-01 23:59 IST
    - cron: "29 18 1 9 *"
  workflow_dispatch:   # optional: lets you trigger manually too

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: 1
          merge-method: merge
